"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { counties } from "./nc-data";
import { countyFipsAt, lookupNcZip, type CountyBoundaries } from "../lib/nc-location";
import { isSnapshot, type NcStatusSnapshotV1, type WeatherAlert } from "../lib/nc-status";
const num = new Intl.NumberFormat("en-US");
const age = (value?: string) => value ? `${Math.max(0, Math.round((Date.now()-Date.parse(value))/60000))} min ago` : "not available";
const rank = (a: WeatherAlert) => (a.severity === "Extreme" ? 0 : a.severity === "Severe" ? 1 : 2) + (a.urgency === "Immediate" ? -1 : 0);
const siteBasePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const snapshotPath = `${siteBasePath}/data/nc-status.json`;
export default function Home() {
 const [data,setData]=useState<NcStatusSnapshotV1|null>(null),[fips,setFips]=useState("37183"),[zip,setZip]=useState(""),[message,setMessage]=useState("Loading official status…"),[layer,setLayer]=useState<"power"|"weather">("power"),[remember,setRemember]=useState(false);
 useEffect(()=>{let live=true;const saved=localStorage.getItem("netpulse-nc-county");if(saved)setTimeout(()=>{if(live){setFips(saved);setRemember(true)}},0);fetch(snapshotPath).then(r=>{if(!r.ok)throw new Error(`snapshot HTTP ${r.status}`);return r.json()}).then(value=>{if(live&&isSnapshot(value))setData(value);if(live)setMessage("Source status loaded. Data age is shown with each source.")}).catch(()=>{if(live)setMessage("Source status is unavailable. Review the source links below.")});return()=>{live=false}},[]);
 const county=counties.find(c=>c.fips===fips)??counties[0], select=(x:string)=>{setFips(x);if(remember)localStorage.setItem("netpulse-nc-county",x)};
 const power=data?.power.find(x=>x.countyFips===fips), alerts=useMemo(()=> (data?.alerts??[]).filter(x=>!x.countyFips.length||x.countyFips.includes(fips)).sort((a,b)=>rank(a)-rank(b)),[data,fips]);
 const unavailable=!data||data.sources.power.freshness!=="fresh"||data.sources.weather.freshness!=="fresh";
 const lookup=(e:FormEvent)=>{e.preventDefault();const found=lookupNcZip(zip);if(found.status==="invalid")return setMessage("Enter a 5-digit NC ZIP code.");if(found.status==="unsupported")return setMessage("That ZIP is not in the local NC lookup. Select a county below.");select(found.fips);setMessage(found.ambiguous?"This ZIP spans counties; the most common county is selected. You may correct it below.":"County selected from the local ZIP lookup.")};
 const locate=()=>{if(!navigator.geolocation)return setMessage("Device location is not available in this browser. Select a county or ZIP instead.");setMessage("Finding your county on this device…");navigator.geolocation.getCurrentPosition(async p=>{try{const response=await fetch(`${siteBasePath}/data/nc-counties.geojson`);if(!response.ok)throw new Error(`boundaries HTTP ${response.status}`);const matched=countyFipsAt(p.coords.longitude,p.coords.latitude,await response.json() as CountyBoundaries);if(!matched)return setMessage("Your location is outside North Carolina or could not be matched. Select a county or ZIP instead.");select(matched);setMessage("County matched on this device. Coordinates were not transmitted or saved.")}catch{setMessage("County boundaries are unavailable. Select a county or ZIP instead.")}},()=>setMessage("Location permission was not granted. Select a county or ZIP instead."),{timeout:8000,maximumAge:300000})};
 return <main><header><a className="brand" href="#dashboard">NetPulse</a><span>North Carolina power outages and weather alerts</span></header>
 <section className="intro" id="dashboard"><p className="eyebrow">Resident status dashboard</p><h1>Know what is affecting your county.</h1><p>Official power and weather information, clear about what is current, stale, or unavailable.</p></section>
 <section className="lookup"><form onSubmit={lookup}><label htmlFor="zip">ZIP code</label><div><input id="zip" value={zip} onChange={e=>setZip(e.target.value.replace(/\D/g,"").slice(0,5))} placeholder="Enter 5-digit NC ZIP" inputMode="numeric" autoComplete="postal-code" pattern="[0-9]{5}" maxLength={5}/><button>Find county</button></div></form><button className="location" type="button" onClick={locate}>Use device location</button><label className="remember"><input type="checkbox" checked={remember} onChange={e=>{setRemember(e.target.checked);if(e.target.checked)localStorage.setItem("netpulse-nc-county",fips);else localStorage.removeItem("netpulse-nc-county")}}/> Remember this county</label></section>
 <p className="announce" aria-live="polite">{message}</p>{unavailable&&<aside className="stale" role="status">Some data is stale or unavailable. NetPulse is not reporting “all clear”; review source timestamps below.</aside>}
 <section className="summary"><div><p className="eyebrow">Selected county</p><h2>{county.name} County</h2></div><article><span>Customers without power</span><strong>{data?.sources.power.freshness==="unavailable"?"Unavailable":power?num.format(power.customersOut):"0"}</strong><small>{power?.percentOut!==undefined?`${power.percentOut.toFixed(1)}% out`:"Percentage not supplied"} · {age(data?.sources.power.lastSuccessAt)}</small></article><article><span>Weather alerts</span><strong>{data?.sources.weather.freshness==="unavailable"?"Unavailable":alerts.length}</strong><small>{alerts[0]?`${alerts[0].severity} · ${alerts[0].event}`:"No active county alerts in fresh data"}</small></article></section>
 <section className="map-section"><div className="map-head"><div><p className="eyebrow">Statewide view</p><h2>North Carolina counties</h2></div><div className="toggle"><button className={layer==="power"?"active":""} onClick={()=>setLayer("power")}>Power outages</button><button className={layer==="weather"?"active":""} onClick={()=>setLayer("weather")}>Weather alerts</button></div></div><div className="county-map" aria-label="Interactive North Carolina county map">{counties.map(c=>{const p=data?.power.find(x=>x.countyFips===c.fips),a=(data?.alerts??[]).filter(x=>x.countyFips.includes(c.fips));const level=layer==="power"?(p?.percentOut??0)>10?"high":(p?.percentOut??0)>0?"medium":"none":a.some(x=>x.severity==="Extreme"||x.severity==="Severe")?"high":a.length?"medium":"none";return <button key={c.fips} className={`county ${level} ${fips===c.fips?"chosen":""}`} style={{left:`${c.x}%`,top:`${c.y}%`}} onClick={()=>select(c.fips)} aria-label={`Select ${c.name} County`}/>})}</div><p className="map-note">Map colors are separate scales for {layer==="power"?"reported customers without power":"official weather severity"}. The county list is an equivalent navigation control.</p><div className="county-list">{counties.map(c=><button className={fips===c.fips?"selected":""} onClick={()=>select(c.fips)} key={c.fips}>{c.name}</button>)}</div></section>
 <section className="details"><article><p className="eyebrow">Power details</p><h2>{county.name} County</h2>{data?.sources.power.freshness==="unavailable"?<p>Current county outage data is unavailable. This does not mean no outages.</p>:<><p className="metric">{power?num.format(power.customersOut):"0"}<span>customers without power</span></p><p>{power?.customersServed?`${num.format(power.customersServed)} customers served · `:""}{power?.percentOut!==undefined?`${power.percentOut.toFixed(1)}% reported out`:"County percentage not supplied"}</p></>}<a href="https://www.ncdps.gov/power-outages">NC DPS outage information</a></article><article><p className="eyebrow">Weather alerts</p><h2>Official NWS alerts</h2>{data?.sources.weather.freshness==="unavailable"?<p>Current weather alert data is unavailable. This does not mean no alerts.</p>:alerts.length?alerts.map(a=><div className="alert" key={a.id}><b>{a.severity} · {a.event}</b><p>{a.headline}</p><small>{a.urgency} · expires {new Date(a.expiresAt).toLocaleString()}</small>{a.instruction&&<p>{a.instruction}</p>}<a href={a.sourceUrl}>View NWS alert</a></div>):<p>No active alerts for this county in fresh NWS data.</p>}</article></section>
 <footer><p>Sources: <a href={data?.sources.power.sourceUrl??"https://www.ncdps.gov/power-outages"}>NC Emergency Management</a> ({data?.sources.power.freshness??"unavailable"}, {age(data?.sources.power.lastSuccessAt)}) and <a href="https://api.weather.gov/alerts/active?area=NC">National Weather Service</a> ({data?.sources.weather.freshness??"unavailable"}, {age(data?.sources.weather.lastSuccessAt)}).</p><p>NetPulse is informational. It does not replace Wireless Emergency Alerts, utility reporting, or emergency services.</p></footer></main>;
}
