import { NCEM_URL, NWS_URL, parseNcem, parseNws, type Freshness, type NcStatusSnapshotV1, unavailableSnapshot } from "../lib/nc-status";
export interface NcEnv { DB?: D1Database }
const POWER_KEY = "nc-power", WEATHER_KEY = "nc-weather";
const statusFor = (lastSuccessAt: string | undefined, maxFresh: number, maxStale: number): Freshness => { if (!lastSuccessAt) return "unavailable"; const age = Date.now() - Date.parse(lastSuccessAt); return age <= maxFresh ? "fresh" : age <= maxStale ? "stale" : "unavailable"; };
async function ensure(db: D1Database) { await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS nc_source_snapshots (source_key TEXT PRIMARY KEY NOT NULL, payload TEXT NOT NULL, checksum TEXT NOT NULL, observed_at TEXT, last_success_at TEXT NOT NULL, last_attempt_at TEXT NOT NULL, failure_category TEXT)"), db.prepare("CREATE TABLE IF NOT EXISTS nc_ingestion_leases (source_key TEXT PRIMARY KEY NOT NULL, expires_at INTEGER NOT NULL)")]); }
type Row = { source_key: string; payload: string; observed_at: string | null; last_success_at: string; last_attempt_at: string; failure_category: string | null };
async function row(db: D1Database, key: string) { await ensure(db); return db.prepare("SELECT * FROM nc_source_snapshots WHERE source_key = ? LIMIT 1").bind(key).first<Row>(); }
const checksum = (text: string) => { let n = 2166136261; for (const c of text) n = Math.imul(n ^ c.charCodeAt(0), 16777619); return String(n >>> 0); };
async function refresh(db: D1Database | undefined, key: string, url: string, parser: (x: unknown) => unknown, headers?: HeadersInit) {
  const attempted = new Date().toISOString();
  try { const response = await fetch(url, { headers }); if (!response.ok) throw new Error(`http-${response.status}`); const payload = parser(await response.json()); const serialized = JSON.stringify(payload); if (db) { await ensure(db); await db.prepare("INSERT INTO nc_source_snapshots (source_key,payload,checksum,observed_at,last_success_at,last_attempt_at,failure_category) VALUES (?,?,?,?,?,?,NULL) ON CONFLICT(source_key) DO UPDATE SET payload=excluded.payload,checksum=excluded.checksum,last_success_at=excluded.last_success_at,last_attempt_at=excluded.last_attempt_at,failure_category=NULL").bind(key, serialized, checksum(serialized), attempted, attempted, attempted).run(); } return payload; } catch (error) { if (db) { const previous = await row(db, key); if (previous) await db.prepare("UPDATE nc_source_snapshots SET last_attempt_at=?, failure_category=? WHERE source_key=?").bind(attempted, error instanceof Error ? error.message.slice(0, 48) : "upstream-failure", key).run(); } return null; }
}
function source(name: string, url: string, record: Row | null, fresh: number, stale: number) { return { name, sourceUrl: url, lastAttemptAt: record?.last_attempt_at ?? new Date().toISOString(), lastSuccessAt: record?.last_success_at, observedAt: record?.observed_at ?? undefined, freshness: statusFor(record?.last_success_at, fresh, stale), failureCategory: record?.failure_category ?? undefined }; }
export async function statusSnapshot(env: NcEnv, refreshDue = false): Promise<NcStatusSnapshotV1> { const base = unavailableSnapshot(); const db = env.DB; let powerRow = db ? await row(db, POWER_KEY) : null, weatherRow = db ? await row(db, WEATHER_KEY) : null; const pDue = !powerRow || Date.now() - Date.parse(powerRow.last_success_at) > 15 * 60_000; const wDue = !weatherRow || Date.now() - Date.parse(weatherRow.last_success_at) > 60_000; if (refreshDue || pDue) await refresh(db, POWER_KEY, NCEM_URL, parseNcem); if (refreshDue || wDue) await refresh(db, WEATHER_KEY, NWS_URL, parseNws, { Accept: "application/geo+json", "User-Agent": "NetPulse (https://github.com/drummer475-94/NetPulse)" }); powerRow = db ? await row(db, POWER_KEY) : powerRow; weatherRow = db ? await row(db, WEATHER_KEY) : weatherRow; const power = powerRow ? JSON.parse(powerRow.payload) : []; const alerts = weatherRow ? JSON.parse(weatherRow.payload) : []; return { ...base, generatedAt: new Date().toISOString(), sources: { power: source("NC Emergency Management", NCEM_URL, powerRow, 45*60_000, 60*60_000), weather: source("National Weather Service", NWS_URL, weatherRow, 5*60_000, 10*60_000) }, power: Array.isArray(power) ? power : [], alerts: Array.isArray(alerts) ? alerts : [] }; }
const headers = () => ({ "content-type": "application/json; charset=utf-8", "cache-control": "public, max-age=60, s-maxage=60, stale-while-revalidate=120", "access-control-allow-origin": "*", "x-content-type-options": "nosniff" });
export async function ncStatusApi(request: Request, env: NcEnv, ctx: { waitUntil(p: Promise<unknown>): void }) { if (request.method !== "GET" && request.method !== "HEAD") return new Response("Method not allowed", { status: 405, headers: { allow: "GET, HEAD" } }); const snapshot = await statusSnapshot(env, false); if (snapshot.sources.power.freshness === "unavailable" || snapshot.sources.weather.freshness === "unavailable") ctx.waitUntil(statusSnapshot(env, true)); return new Response(request.method === "HEAD" ? null : JSON.stringify(snapshot), { status: 200, headers: headers() }); }
export async function healthApi(request: Request, env: NcEnv) { const snapshot = await statusSnapshot(env, false); return Response.json({ version: "nc-v1", generatedAt: snapshot.generatedAt, sources: snapshot.sources }, { headers: headers() }); }
